BEGIN;

CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name text,
  email text,
  password text
);

COMMIT;

CREATE TABLE accounts (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  number int,
  label text,
  value int,
  class int
);

INSERT INTO accounts (number, label, value, class) VALUES
('70610000', 'FRANCE TVA 20%', 135.12, 7),
('70620000', 'MONACO TVA 20%', 747.52, 7),
('70630000', 'UE TVA 20%', 1548.56, 7),
('70631000', 'UE EXO', 2569.25, 7),
('70641000', 'EXPORT EXO', 8659.1, 7),
('70963100', 'RRR UE EXO', -896, 7);
