CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  email text,
  password text
);

CREATE TABLE accounts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journal text,
  date text,
  number text,
  label text,
  debit int,
  credit int,
  lettering text,
  total int
);