CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname text NOT NULL,
  lastname text NOT NULL,
  email text NOT NULL UNIQUE,
  password text NOT NULL
);

CREATE TABLE accounts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journal TEXT,
  date DATE,
  number TEXT,
  label TEXT,
  debit NUMERIC (9,2),
  credit NUMERIC (9,2),
  lettering TEXT,
  total NUMERIC (9,2)
);